server:
  port: 8080

logging:
  config: classpath:logback/logback-spring.xml

#最好用命令行参数
# TODO  密码加密问题
#spring:
#  datasource:
#    # mysql
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/archessm?serverTimezone=Asia/Shanghai
#    username: your mysql username
#    password: your mysql pass