server:
  port: 8081

spring:
  datasource:
    # memory h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:archessm;MODE=mysql;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS archessm\;SET SCHEMA archessm
    username: sa
    password:

mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
  - classpath:mapper/h2/*.xml

logging:
  level:
    indi:
      daniel:
        archessm:
          dao: debug