server:
  port: 8080

swagger:
  enable: true
  base-package: indi.daniel.archessm.controller
  title: API documentation
  description: Description of API documentation
  version: V1.0

spring:
  datasource:
#    # mysql
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/archessm?serverTimezone=Asia/Shanghai
#    username: your mysql username
#    password: your mysql pass
    # file h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/db/archessm;MODE=mysql;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS archessm\;SET SCHEMA archessm
#    # memory h2
#    url: jdbc:h2:mem:archessm;MODE=mysql;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS archessm\;SET SCHEMA archessm
    username: sa
    password:
