spring:
  profiles:
    active: dev

swagger:
  base-package: indi.daniel.archessm.controller
  title: API documentation
  description: Description of API documentation
  version: V1.0
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
  - classpath:mapper/mysql/*.xml
  type-handlers-package: indi.daniel.achessm.common.mybatis.typehandler
