server:
  port: 8081

spring:
  datasource:
    # file h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/db/archessm;MODE=mysql;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS archessm\;SET SCHEMA archessm
#    # memory h2
#    url: jdbc:h2:mem:archessm;MODE=mysql;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS archessm\;SET SCHEMA archessm
    username: sa
    password:
    druid:
      connection-properties: config.decrypt=false

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:mapper/auth/*.xml
    - classpath:mapper/auth/auto/*.xml
    - classpath:mapper/finance/*.xml
    - classpath:mapper/finance/auto/*.xml
    - classpath:mapper/h2/*.xml


logging:
  level:
    root: info
    druid: debug
    indi:
      daniel:
        archessm:
          dao: debug

